
/**
 * Enumerated Token Types of the Core Language  
 * @author Sid Gowda
 *
 */

public enum TokenType {
	PROGRAM, BEGIN, END, INT, ID, CONSTANT, SEMICOLON, COMMA, ASSIGN, INPUT, OUTPUT, IF, ELSE, THEN, ENDIF, DO, WHILE, ENDDO, AND,
	OR,CASE, COLON, BAR, ADD_OP, SUBT_OP, MULT_OP, GREATER_THAN, GREATER_OR_EQ_TO, EQUAL, NOT, NOT_EQUAL, LESS_THAN, LESS_THAN_OR_EQ_TO,
	LPAREN, RPAREN, LBRACKET, RBRACKET, OF, SCANNER_ERROR, EOF
}
